# Generated by Django 5.0.7 on 2024-08-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-date'], name='my_app_post_date_43a3eb_idx'),
        ),
    ]
